plugins {
	id 'java-library'
	id 'net.neoforged.moddev' version '2.0.140'
	id 'maven-publish'
}

version = project.mod_version
group = project.mod_group_id

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()

	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
	}

	maven {
		name = "CurseMaven"
		url = "https://www.cursemaven.com"
	}
}

neoForge {
	version = project.neo_version
	validateAccessTransformers = true

	runs {
		client {
			client()
		}

		server {
			server()
			programArgument "--nogui"
		}
	}

	mods {
		cobbleexport {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
	implementation "maven.modrinth:cobblemon:${project.cobblemon_version_id}"
	compileOnly "org.jetbrains.kotlin:kotlin-stdlib:${project.kotlin_version}"
	runtimeOnly "curse.maven:kotlin-for-forge-351264:${project.kotlin_for_forge_file_id}"
}

processResources {
	def replaceProperties = [
		minecraft_version: project.minecraft_version,
		minecraft_version_range: project.minecraft_version_range,
		neo_version: project.neo_version,
		neo_version_range: project.neo_version_range,
		loader_version_range: project.loader_version_range,
		mod_id: project.mod_id,
		mod_name: project.mod_name,
		mod_license: project.mod_license,
		mod_version: project.mod_version,
		mod_authors: project.mod_authors,
		mod_description: project.mod_description,
		cobblemon_version_range: project.cobblemon_version_range
	]
	inputs.properties replaceProperties

	filesMatching("META-INF/neoforge.mods.toml") {
		expand replaceProperties
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}" }
	}

	manifest {
		attributes([
			"Specification-Title": project.mod_id,
			"Specification-Vendor": project.mod_authors,
			"Specification-Version": "1",
			"Implementation-Title": project.mod_name,
			"Implementation-Version": project.jar.archiveVersion,
			"Implementation-Vendor": project.mod_authors
		])
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name.toString()
			from components.java
		}
	}

	repositories {
	}
}
