modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Sythiex/Cobblemon-Export/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayTest="IGNORE_ALL_VERSION"
logoFile="assets/cobbleexport/icon.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="cobblemon"
type="required"
versionRange="${cobblemon_version_range}"
ordering="AFTER"
side="CLIENT"

[features.${mod_id}]
javaVersion="[21,)"
